version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
words:
  - Anatomia
  - anio
  - anios
  - Aritmeticos
  - Asignacion
  - calificacion
  - caracter
  - celsius
  - codigo
  - Comparacion
  - Computacion
  - creditos
  - CUCEI
  - decrementarlo
  - dias
  - digito
  - digitos
  - dinamica
  - direccion
  - Direccion
  - estatica
  - Exupéry
  - farenheit
  - Farenheit
  - Foquito
  - ganá
  - Informatica
  - Inscripcion
  - Jeshua
  - kardex
  - kilometro
  - kilometros
  - lenguage
  - Logicas
  - Lopez
  - metodo
  - Miercoles
  - Multiplicacion
  - Notacion
  - numeros
  - parametros
  - Perez
  - Principito
  - Programacion
  - rectangulo
  - Reynozo
  - Sabado
  - Situacion
  - sobreescritura
  - tendra
  - terminos
  - ULAM
ignoreWords: []
import: []
enabled: true
